// ────────────────────────────────────────────────────────────────────────────
// SEFAES PHASE 2 — COMMAND CONTRACT LAYER
// Every operation in the system MUST conform to these contracts.
// No command executes without a traceId, a typed payload, and a known source.
// No response is allowed to be undefined or untraced.
// ────────────────────────────────────────────────────────────────────────────

/**
 * Every command dispatched through the CommandBus MUST conform to this type.
 * The `traceId` is generated by the caller via `generateTraceId()`.
 */
export type Command<TPayload = Record<string, unknown>> = {
    /** The command type string — MUST be from COMMANDS registry */
    type: string;
    /** The command payload — strongly typed per command */
    payload: TPayload;
    /** Globally unique trace identifier for full observability */
    traceId: string;
    /** Origin of the command */
    source: 'ui' | 'system' | 'queue';
    /** Unix epoch milliseconds */
    timestamp: number;
};

/**
 * Every response returned from the CommandBus MUST conform to this type.
 * No undefined returns are allowed.
 */
export type CommandResponse<T = any> = {
    success: boolean;
    data?: T;
    error?: CommandError;
    traceId: string;
};

/**
 * Standardized error object.
 * - `message`: Human-readable, safe to display in UI.
 * - `code`: Machine-readable for programmatic handling.
 * - `traceId`: Reference for debugging and support.
 */
export type CommandError = {
    message: string;
    code: string;
    traceId: string;
};

// ── Script Pipeline States ───────────────────────────────────────────────────
export type ScriptPipelineState =
    | 'uploaded'
    | 'ocr_processing'
    | 'ocr_complete'
    | 'grading'
    | 'graded'
    | 'failed';

/**
 * A script job represents a single student answer script moving through
 * the processing pipeline. States must be traversed in order.
 */
export type ScriptJob = {
    jobId: string;
    traceId: string;
    studentId: string;
    examId: string;
    teacherId: string;
    schoolId: string;
    fileUrl: string;
    ocrText?: string;
    state: ScriptPipelineState;
    error?: CommandError;
    createdAt: number;
    updatedAt: number;
    retryCount: number;
};

// ── Audit Log Entry ──────────────────────────────────────────────────────────
export type AuditEntry = {
    traceId: string;
    actor: string;
    action: string;
    status: 'DISPATCHED' | 'SUCCESS' | 'FAILURE';
    payload?: Record<string, unknown>;
    error?: string;
    timestamp: number;
};
