export const CBTCommandTypes = {
    CBT_START_SESSION:   'CBT.START_SESSION',
    CBT_LOAD_EXAM:       'CBT.LOAD_EXAM',
    CBT_BEGIN_EXAM:      'CBT.BEGIN_EXAM',
    CBT_SUBMIT_ANSWER:   'CBT.SUBMIT_ANSWER',
    CBT_NEXT_QUESTION:   'CBT.NEXT_QUESTION',
    CBT_PAUSE_SESSION:   'CBT.PAUSE_SESSION',
    CBT_RESUME_SESSION:  'CBT.RESUME_SESSION',
    CBT_AUTO_SUBMIT:     'CBT.AUTO_SUBMIT',
    CBT_RESTORE_SESSION: 'CBT.RESTORE_SESSION',
    CBT_SYNC_STATE:      'CBT.SYNC_STATE',
} as const;

export type CBTCommandType = typeof CBTCommandTypes[keyof typeof CBTCommandTypes];
