export const ResultCommandTypes = {
    RESULT_READ: 'RESULT.READ',
    RESULT_STATUS_READ: 'RESULT.STATUS_READ',
    RESULT_START_GRADING: 'RESULT.START_GRADING',
    STORAGE_UPLOAD: 'RESULT.STORAGE_UPLOAD',
    ANSWER_SCRIPT_CREATE: 'RESULT.ANSWER_SCRIPT_CREATE',
    OCR_PROCESS: 'RESULT.OCR_PROCESS',
    FINALIZE_GRADING: 'RESULT.FINALIZE_GRADING',
    RETRY_GRADING: 'RESULT.RETRY_GRADING',
    GENERATE_INSIGHTS: 'RESULT.GENERATE_INSIGHTS',
    RESULT_FAIL_GRADING: 'RESULT.FAIL_GRADING',
} as const;

export type ResultCommandType = typeof ResultCommandTypes[keyof typeof ResultCommandTypes];
