export const StudentCommandTypes = {
    STUDENT_ENROLL: 'STUDENT.ENROLL',
    STUDENT_DEACTIVATE: 'STUDENT.DEACTIVATE',
    STUDENT_TRANSFER_CLASS: 'STUDENT.TRANSFER_CLASS',
    STUDENT_READ: 'STUDENT.READ',
    STUDENTS_BULK_CREATE: 'STUDENT.BULK_CREATE',
    CLASSES_READ: 'STUDENT.CLASSES_READ',
    CLASSES_CREATE: 'STUDENT.CLASSES_CREATE',
    CLASSES_DELETE: 'STUDENT.CLASSES_DELETE',
    SUBJECTS_READ: 'STUDENT.SUBJECTS_READ',
    SUBJECTS_CREATE: 'STUDENT.SUBJECTS_CREATE',
    CLASS_SUBJECTS_READ: 'STUDENT.CLASS_SUBJECTS_READ',
    CLASS_SUBJECTS_CREATE: 'STUDENT.CLASS_SUBJECTS_CREATE',
    CLASS_SUBJECTS_DELETE: 'STUDENT.CLASS_SUBJECTS_DELETE',
} as const;

export type StudentCommandType = typeof StudentCommandTypes[keyof typeof StudentCommandTypes];
